os: linux
language: ruby
rvm:
  - 2.6.4

services:
  - postgresql

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

install:
  - bundle install --jobs 3 --retry 3
  - nvm install 10
  - node -v
  - npm i -g yarn
  - yarn

before_script:
  - bundle exec rake assets:precompile

script:
  - bundle exec rake db:create db:migrate
  - bundle exec rspec

after_script:
  - docker build -t dokku/mcq .
