# RVM: https://andycroll.com/ruby/github-actions-ci-for-rails-with-specific-ruby-versions/

name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - name: Setup Ruby
        run: |
          curl -sSL https://get.rvm.io | bash
          source $HOME/.rvm/scripts/rvm

          rvm install $(cat .ruby-version) --binary
          rvm --default use $(cat .ruby-version)
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Build and run tests
        env:
          DATABASE_URL: postgres://postgres:@localhost:5432/mcq_test
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          sudo apt-get -yqq install libpq-dev
          source $HOME/.rvm/scripts/rvm
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake assets:precompile
          bundle exec rails db:prepare
          bundle exec rspec
      - name: Build Docker image
        run: |
          docker build -t dokku/mcq .
